CREATE TABLE PLAYERS(
    ID INT NOT NULL AUTO_INCREMENT,
     PLAYERID VARCHAR2(4)  AS ( 'P' || TO_CHAR(ID, 'FM099')),
    NAME VARCHAR2(255) NOT NULL,
    MAIL VARCHAR2(255),
    PHONE LONG,
   ACTIVEIND INT DEFAULT 1,
   UPDATE_DT_TM DATETIME DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (ID,PLAYERID ));


CREATE TABLE ENTRIES(
ID INT NOT NULL AUTO_INCREMENT,
PLAYERID VARCHAR2(4) , 
ENTRYID VARCHAR2(6)   AS ( 'E' || TO_CHAR(ID, 'FM09999')),
DERBYWEIGHT DOUBLE,
 ACTIVEIND INT DEFAULT 1,
   UPDATE_DT_TM DATETIME DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (ID,ENTRYID ),
 FOREIGN KEY(PLAYERID) REFERENCES PLAYERS(PLAYERID) );


CREATE TABLE Fights(
    ID INT NOT NULL AUTO_INCREMENT,
     FIGHTID INT NOT NULL,
    PLAYER VARCHAR2(255) NOT NULL,
ENTRY VARCHAR2(255) NOT NULL,
FIGHTSTATUS VARCHAR2(255) NOT NULL,
POINTS INT NOT NULL,
   ACTIVEIND INT DEFAULT 1,
   UPDATE_DT_TM DATETIME DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (ID,FIGHTID));



SELECT P.PLAYERID,P.NAME,E.ENTRYID,E.DERBYWEIGHT,P.UPDATE_DT_TM FROM PLAYERS P
JOIN ENTRIES E ON E.PLAYERID = P.PLAYERID 
WHERE P.UPDATE_DT_TM LIKE (select to_char (SYSDATE, 'MM-DD-YYYY') from dual)
ORDER BY P.PLAYERID;


select to_char (SYSDATE, 'MM-DD-YYYY') from dual;




INSERT INTO Fights( FIGHTID,PLAYER1,ENTRY1,PLAYER2,ENTRY2,FIGHTSTATUS,WONBY,POINTS) VALUES 
(1,'P001','E001','P002','E002','WON','PLAYER2',2);



UPDATE ENTRIES SET ACTIVEIND = 0 
WHERE ENTRYID = 'E00001';


INSERT INTO PLAYERS (NAME,MAIL,PHONE,ACTIVEIND) 
VALUES ('REMO','REMO@GMAIL.COM',82648242,1);
SELECT * FROM PLAYERS;

INSERT INTO ENTRIES (PLAYERID,DERBYWEIGHT)
VALUES ('P001',4.5);

INSERT INTO ENTRIES (PLAYERID,DERBYWEIGHT)
VALUES ('P001',6);

INSERT INTO ENTRIES (PLAYERID,DERBYWEIGHT)
VALUES ('P002',2.2);





INSERT INTO ENTRIES (PLAYERID,DERBYWEIGHT)
VALUES ('P003',5.2);


INSERT INTO ENTRIES (PLAYERID,DERBYWEIGHT)
VALUES ('P003',6);


INSERT INTO ENTRIES (PLAYERID,DERBYWEIGHT)
VALUES ('P003',4.8);

INSERT INTO ENTRIES (PLAYERID,DERBYWEIGHT)
VALUES ('P002',7.1);



SELECT P.PLAYERID,P.NAME,P.PHONE,P.ACTIVEIND AS PLAYERACTIVE,E.ENTRYID,E.DERBYWEIGHT,E.ACTIVEIND AS ENTRYACTIVE
 FROM PLAYERS P JOIN ENTRIES E ON P.PLAYERID = E.PLAYERID ORDER BY P.PLAYERID
 
 
 
 
SELECT  A.ENTRYID, B.ENTRYID,A.PLAYERID,B.PLAYERID
FROM ENTRIES A
INNER JOIN ENTRIES  B ON A.PLAYERID <> B.PLAYERID




select distinct a.entryid, b.entryid ,a.playerid,b.playerid from entries a
join entries b  on a.playerid <> b.playerid and a.entryid <> b.entryid

